# Generated by Django 4.2.11 on 2024-06-13 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('niger_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='surveyor',
        ),
        migrations.AlterField(
            model_name='documents',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
